name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup iOS dependencies
      run: |
        cd ios
        pod repo update
        pod install --repo-update
        cd ..
        
    - name: Build iOS (unsigned - for testing)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Archive iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: |
          build/ios/iphoneos/Runner.app
          ios/Runner.xcworkspace
        retention-days: 30
        
    - name: Create build summary
      run: |
        echo "## iOS Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "✅ iOS build completed successfully!" >> $GITHUB_STEP_SUMMARY
        echo "📱 Build artifacts uploaded and ready for download" >> $GITHUB_STEP_SUMMARY
        echo "📋 Next steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Download build artifacts from the Actions tab" >> $GITHUB_STEP_SUMMARY
        echo "2. Transfer to a Mac for signing and deployment" >> $GITHUB_STEP_SUMMARY
        echo "3. Open ios/Runner.xcworkspace in Xcode" >> $GITHUB_STEP_SUMMARY
        echo "4. Configure signing and deploy to iPhone" >> $GITHUB_STEP_SUMMARY
